
trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm ci
      npm run build
      npm run package
    displayName: 'npm install and build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'web-ext-artifacts/'
      artifactName: extension

- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      # ff_nightly:
      #   firefox_base_url: "https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/"
      #   firefox_distribution: "firefox-71.0a1.en-US.linux-x86_64.tar.bz2"
      ff_67:
        firefox_base_url: "https://ftp.mozilla.org/pub/devedition/releases/67.0b19/linux-x86_64/en-GB/"
        firefox_distribution: "firefox-67.0b19.tar.bz2"
      ff_68:
        firefox_base_url: "https://ftp.mozilla.org/pub/devedition/releases/68.0b14/linux-x86_64/en-GB/"
        firefox_distribution: "firefox-68.0b14.tar.bz2"
      ff_69:
        firefox_base_url: "https://ftp.mozilla.org/pub/devedition/releases/69.0b16/linux-x86_64/en-GB/"
        firefox_distribution: "firefox-69.0b16.tar.bz2"
      ff_70:
        firefox_base_url: "https://ftp.mozilla.org/pub/devedition/releases/70.0b4/linux-x86_64/en-GB/"
        firefox_distribution: "firefox-70.0b4.tar.bz2"
      ff_71:
        firefox_base_url: "https://ftp.mozilla.org/pub/devedition/releases/71.0b12/linux-x86_64/en-GB/"
        firefox_distribution: "firefox-71.0b12.tar.bz2"
      ff_72:
        firefox_base_url: "https://ftp.mozilla.org/pub/devedition/releases/72.0b2/linux-x86_64/en-GB/"
        firefox_distribution: "firefox-72.0b2.tar.bz2"
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      wget "$(firefox_base_url)$(firefox_distribution)"
      tar -xf $(firefox_distribution)
      chmod +x ./firefox/firefox-bin
      npm install -g tap-xunit
      npm ci
    displayName: 'Setup testing environment'
  - script: 
      MOZ_BINARY=./firefox/firefox-bin npm run test | tap-xunit > ./test-results.xml
    displayName: 'Test'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: './test-results.xml'
      testRunTitle: $(Agent.JobName)
